services:
  sso_backend:
    image: sso-backend
    container_name: sso-backend
    build:
      context: ${PATH_TO_SSO_BACKEND}
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_PORT: ${SSO_DB_PORT}
      DB_HOST: ${SSO_DB_HOST}
      DB_NAME: ${SSO_DB_NAME}
      DB_USER: ${SSO_DB_USER}
      DB_PASSWORD: ${SSO_DB_PASSWORD}
      BASE_URL: "http://localhost:8080"
      ALLOW_ORIGINS: "*"
      FRONTEND_URL: "http://localhost:3000"
      CORS_ALLOW_CREDENTIALS: "true"
      CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      CORS_ALLOW_HEADERS: "Content-Type,Authorization"
    env_file:
      - .env


  accounts:
    image: accounts
    container_name: accounts
    build:
      context: ${PATH_TO_ACCOUNTS}
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      API_URL: "http://localhost:8080"
      FRONTEND_URL: "http://localhost:3000"
    depends_on:
      - sso_backend
    env_file:
      - .env
