name: "Bug Report"
description: "Report a bug with details for debugging test"
title: "[BUG] "
labels: ["bug"]
# projects: ["WeirdBrains/your-project"] # Replace with your actual GitHub project ID
body:
  - type: markdown
    attributes:
      value: "### Please complete all required fields before submitting."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a detailed description of the bug, including steps to reproduce, expected behavior, and actual behavior."
      placeholder: "Describe the issue here..."

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: "Complexity"
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
    validations:
      required: true
