version: '3.8'

services:
  # PostgreSQL database for both services (using existing containers)
  # Note: We're using host.docker.internal to connect to the existing PostgreSQL containers
  
  # SSO Backend service
  sso_backend:
    build:
      context: ../../sso_backend
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_NAME=sso_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SSL=false
      - SENDGRID_API_KEY=
      - SENDGRID_INVITE_TEMPLATE_ID=
      - SENDGRID_RESET_PASSWORD_TEMPLATE_ID=
      - SENDGRID_RESET_PASSWORD_URL=
      - SENDGRID_FROM_EMAIL=
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Main Backend service
  backend:
    build:
      context: ../../backend
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=mandible_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SSL=false
    ports:
      - "8090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - sso_backend

  # Accounts Flutter web app
  accounts:
    image: ghcr.io/cirruslabs/flutter:3.29.1
    volumes:
      - ../../accounts:/app
    working_dir: /app
    command: bash -c "flutter pub get && flutter build web && mkdir -p /app/build_output && cp -r build/web/* /app/build_output/"
    environment:
      - SSO_BACKEND_URL=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - sso_backend

  # Nginx for Accounts web app
  accounts_web:
    image: nginx:1.21.1-alpine
    ports:
      - "8000:80"
    volumes:
      - ../../accounts/build_output:/usr/share/nginx/html
    depends_on:
      - accounts

  # Mandible Flutter web app
  mandible:
    image: ghcr.io/cirruslabs/flutter:3.29.1
    volumes:
      - ../../mandible:/app
    working_dir: /app
    command: bash -c "flutter pub get && flutter build web && mkdir -p /app/build_output && cp -r build/web/* /app/build_output/"
    environment:
      - BACKEND_URL=http://host.docker.internal:8090
      - SSO_URL=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      - sso_backend

  # Nginx for Mandible web app
  mandible_web:
    image: nginx:1.21.1-alpine
    ports:
      - "8001:80"
    volumes:
      - ../../mandible/build_output:/usr/share/nginx/html
    depends_on:
      - mandible

volumes:
  accounts_web_build:
  mandible_web_build:
